// =============================================
// iconPacks.jsx — Multi-library icon pack system
// Maps semantic icon names to each library's components.
// All icons must accept: size (number) and style (object).
// =============================================
import React from "react";

// --- Lucide React (default) ---
import {
  TrendingUp as LuTrendingUp,
  DollarSign as LuDollarSign,
  Filter as LuFilter,
  User as LuUser,
  RefreshCw as LuRefreshCw,
  LayoutGrid as LuLayoutGrid,
  List as LuList,
  Settings as LuSettings,
  X as LuX,
  Calendar as LuCalendar,
  Timer as LuTimer,
  Plus as LuPlus,
  Pencil as LuPencil,
  Download as LuDownload,
  Search as LuSearch,
  Trash2 as LuTrash2,
  ChevronLeft as LuChevronLeft,
  ChevronRight as LuChevronRight,
  ChevronDown as LuChevronDown,
} from "lucide-react";

// --- Phosphor Icons ---
import {
  ChartLineUp as PhTrending,
  CurrencyDollar as PhDollar,
  Funnel as PhFilter,
  User as PhUser,
  ArrowClockwise as PhRefresh,
  SquaresFour as PhGrid,
  List as PhList,
  GearSix as PhSettings,
  X as PhX,
  Calendar as PhCalendar,
  Timer as PhTimer,
  Plus as PhPlus,
  PencilSimple as PhPencil,
  DownloadSimple as PhDownload,
  MagnifyingGlass as PhSearch,
  Trash as PhTrash,
  CaretLeft as PhCaretLeft,
  CaretRight as PhCaretRight,
  CaretDown as PhCaretDown,
} from "@phosphor-icons/react";

// --- Tabler Icons ---
import {
  IconTrendingUp as TaTablerTrend,
  IconCurrencyDollar as TaDollar,
  IconFilter as TaFilter,
  IconUser as TaUser,
  IconRefresh as TaRefresh,
  IconLayoutGrid as TaGrid,
  IconList as TaList,
  IconSettings as TaSettings,
  IconX as TaX,
  IconCalendar as TaCalendar,
  IconClock as TaClock,
  IconPlus as TaPlus,
  IconPencil as TaPencil,
  IconDownload as TaDownload,
  IconSearch as TaSearch,
  IconTrash as TaTrash,
  IconChevronLeft as TaChevLeft,
  IconChevronRight as TaChevRight,
  IconChevronDown as TaChevDown,
} from "@tabler/icons-react";

// --- Heroicons (size not natively supported → wrapper converts to width/height) ---
import {
  ArrowTrendingUpIcon as HeroTrend,
  CurrencyDollarIcon as HeroDollar,
  FunnelIcon as HeroFilter,
  UserIcon as HeroUser,
  ArrowPathIcon as HeroRefresh,
  Squares2X2Icon as HeroGrid,
  ListBulletIcon as HeroList,
  Cog6ToothIcon as HeroSettings,
  XMarkIcon as HeroX,
  CalendarIcon as HeroCalendar,
  ClockIcon as HeroClock,
  PlusIcon as HeroPlus,
  PencilIcon as HeroPencil,
  ArrowDownTrayIcon as HeroDownload,
  MagnifyingGlassIcon as HeroSearch,
  TrashIcon as HeroTrash,
  ChevronLeftIcon as HeroChevLeft,
  ChevronRightIcon as HeroChevRight,
  ChevronDownIcon as HeroChevDown,
} from "@heroicons/react/24/outline";

// Heroicons wrapper: converts `size` prop → style width/height
const hw = (Comp) => ({ size, style, ...rest }) =>
  React.createElement(Comp, { style: { width: size, height: size, flexShrink: 0, ...style }, ...rest });

// --- Font Awesome (via react-icons/fa6) ---
import {
  FaChartLine,
  FaDollarSign,
  FaFilter as FaFilt,
  FaUser,
  FaRotate,
  FaBorderAll,
  FaBars,
  FaGear,
  FaXmark,
  FaCalendar,
  FaClock,
  FaPlus,
  FaPencil,
  FaDownload,
  FaMagnifyingGlass,
  FaTrash,
  FaChevronLeft,
  FaChevronRight,
  FaChevronDown,
} from "react-icons/fa6";

// --- HugeIcons ---
import {
  Chart02Icon as HugeChartIcon,
  DollarCircleIcon as HugeDollar,
  FilterIcon as HugeFilter,
  UserIcon as HugeUser,
  ArrowReloadHorizontalIcon as HugeRefresh,
  GridViewIcon as HugeGrid,
  ListViewIcon as HugeList,
  Settings01Icon as HugeSettings,
  Cancel01Icon as HugeX,
  Calendar01Icon as HugeCalendar,
  Timer01Icon as HugeTimer,
  Add01Icon as HugePlus,
  PencilIcon as HugePencil,
  Download01Icon as HugeDownload,
  Search01Icon as HugeSearch,
  Delete01Icon as HugeTrash,
  ArrowLeft01Icon as HugeChevLeft,
  ArrowRight01Icon as HugeChevRight,
  ArrowDown01Icon as HugeChevDown,
} from "hugeicons-react";

// =============================================
// Pack definitions — each pack maps the 19 semantic
// icon names used in App.jsx to its library's component.
// =============================================
export const ICON_PACKS = {
  lucide: {
    label: "Lucide",
    TrendingUp: LuTrendingUp,
    DollarSign: LuDollarSign,
    Filter: LuFilter,
    User: LuUser,
    RefreshCw: LuRefreshCw,
    LayoutGrid: LuLayoutGrid,
    List: LuList,
    Settings: LuSettings,
    X: LuX,
    Calendar: LuCalendar,
    Timer: LuTimer,
    Plus: LuPlus,
    Pencil: LuPencil,
    Download: LuDownload,
    Search: LuSearch,
    Trash2: LuTrash2,
    ChevronLeft: LuChevronLeft,
    ChevronRight: LuChevronRight,
    ChevronDown: LuChevronDown,
  },
  phosphor: {
    label: "Phosphor",
    TrendingUp: PhTrending,
    DollarSign: PhDollar,
    Filter: PhFilter,
    User: PhUser,
    RefreshCw: PhRefresh,
    LayoutGrid: PhGrid,
    List: PhList,
    Settings: PhSettings,
    X: PhX,
    Calendar: PhCalendar,
    Timer: PhTimer,
    Plus: PhPlus,
    Pencil: PhPencil,
    Download: PhDownload,
    Search: PhSearch,
    Trash2: PhTrash,
    ChevronLeft: PhCaretLeft,
    ChevronRight: PhCaretRight,
    ChevronDown: PhCaretDown,
  },
  tabler: {
    label: "Tabler",
    TrendingUp: TaTablerTrend,
    DollarSign: TaDollar,
    Filter: TaFilter,
    User: TaUser,
    RefreshCw: TaRefresh,
    LayoutGrid: TaGrid,
    List: TaList,
    Settings: TaSettings,
    X: TaX,
    Calendar: TaCalendar,
    Timer: TaClock,
    Plus: TaPlus,
    Pencil: TaPencil,
    Download: TaDownload,
    Search: TaSearch,
    Trash2: TaTrash,
    ChevronLeft: TaChevLeft,
    ChevronRight: TaChevRight,
    ChevronDown: TaChevDown,
  },
  heroicons: {
    label: "Heroicons",
    TrendingUp: hw(HeroTrend),
    DollarSign: hw(HeroDollar),
    Filter: hw(HeroFilter),
    User: hw(HeroUser),
    RefreshCw: hw(HeroRefresh),
    LayoutGrid: hw(HeroGrid),
    List: hw(HeroList),
    Settings: hw(HeroSettings),
    X: hw(HeroX),
    Calendar: hw(HeroCalendar),
    Timer: hw(HeroClock),
    Plus: hw(HeroPlus),
    Pencil: hw(HeroPencil),
    Download: hw(HeroDownload),
    Search: hw(HeroSearch),
    Trash2: hw(HeroTrash),
    ChevronLeft: hw(HeroChevLeft),
    ChevronRight: hw(HeroChevRight),
    ChevronDown: hw(HeroChevDown),
  },
  fontawesome: {
    label: "Font Awesome",
    TrendingUp: FaChartLine,
    DollarSign: FaDollarSign,
    Filter: FaFilt,
    User: FaUser,
    RefreshCw: FaRotate,
    LayoutGrid: FaBorderAll,
    List: FaBars,
    Settings: FaGear,
    X: FaXmark,
    Calendar: FaCalendar,
    Timer: FaClock,
    Plus: FaPlus,
    Pencil: FaPencil,
    Download: FaDownload,
    Search: FaMagnifyingGlass,
    Trash2: FaTrash,
    ChevronLeft: FaChevronLeft,
    ChevronRight: FaChevronRight,
    ChevronDown: FaChevronDown,
  },
  hugeicons: {
    label: "HugeIcons",
    TrendingUp: HugeChartIcon,
    DollarSign: HugeDollar,
    Filter: HugeFilter,
    User: HugeUser,
    RefreshCw: HugeRefresh,
    LayoutGrid: HugeGrid,
    List: HugeList,
    Settings: HugeSettings,
    X: HugeX,
    Calendar: HugeCalendar,
    Timer: HugeTimer,
    Plus: HugePlus,
    Pencil: HugePencil,
    Download: HugeDownload,
    Search: HugeSearch,
    Trash2: HugeTrash,
    ChevronLeft: HugeChevLeft,
    ChevronRight: HugeChevRight,
    ChevronDown: HugeChevDown,
  },
};

export const ICON_PACK_KEYS = Object.keys(ICON_PACKS);
